package com.jinman.entity;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.age
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gender
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.age
     *
     * @return the value of t_goods.age
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.age
     *
     * @param age the value for t_goods.age
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.gender
     *
     * @return the value of t_goods.gender
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.gender
     *
     * @param gender the value for t_goods.gender
     *
     * @mbg.generated Fri Jun 15 17:04:50 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }
}